frontend/controllers/DashboardController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

// Models 
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Contact;
use frontend\models\User;
use frontend\models\Person;



/**
 * Site controller
 */
class DashboardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
		
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
		
        return $this->render('index');
    }
	
	public function actionProfile()
    {
		
		$contact = new Contact();
		$person = new Person();
		$user = new User();
		$getPerson = $person->find()->where(['user_id' => Yii::$app->user->identity->id])->one();
		$getContact = $contact->find()->where(['user_id' => Yii::$app->user->identity->id])->one();
		$getUser = $user;
		$getAllUsersDetails =  $user->find()->where(['id' => Yii::$app->user->identity->id])->one();
		if(empty($getContact) ){
			$getContact = $contact;
		}
		if(empty($getPerson) ){
			$getPerson = $person;
		}
		
        return $this->render('profile',[
			'contactModel' => $getContact,
			'personModel' => $getPerson,
			'userModel' => $getUser,
			'userDetails' => $getAllUsersDetails,
			
		]);
    }
	
	public function actionProfilesave()
    {
		
		$contact = new Contact();
		$person = new Person();
		$getPerson = $person->find()->where(['user_id' => Yii::$app->user->identity->id])->one();
		$getContact = $contact->find()->where(['user_id' => Yii::$app->user->identity->id])->one();
		if(empty($getContact) ){
			$getContact = $contact;
		}
		if(empty($getPerson) ){
			$getPerson = $person;
		}
		$getPerson->user_id = yii::$app->user->identity->id ;
		$getContact->user_id = yii::$app->user->identity->id;
		if($getPerson->load(Yii::$app->request->post()) and $getContact->load(Yii::$app->request->post())){
			$getPerson->save(false);
			$getContact->save(false);
			return ['success'=>'true', 'status'=>1];
			
			
		}
        
    }
	public function actionFundwallet(){
		$user = new User();
		$getUser = $user->findOne(Yii::$app->user->identity->id);
		
		
		
		$wallets = $_POST['User']['wallet'] + $getUser->wallet;
		$getUser->wallet = $wallets;
		$getUser->save(false);
		
		return 1;
		

		
	}

  
}

frontend/views/dashboard/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\bootstrap\Modal;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
	.dashicons{
		width: 100%;
		
	}
	.dashiconheightlast{
		height: 160px;
	}
</style>
<div class="dasgboard-index">

	<section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">

		  <a href='<?=Url::to(['data/index']) ?>' >

			  <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
			  <?=Html::img("@web/images/databundle.png", ["alt" => "loader","id"=>"", "class" => "dashicons" ]) ?>
            <div class="inner">
             <!-- <h3>Buy Data Bundle</h3>-->

              <p > Start enjoying this very low rates for your internet browsing databundle.
</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <a href='<?=Url::to(["data/index"]) ?>'  class="small-box-footer">Buy Now <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
		  </a>
		  

		  <a href='<?=Url::to(['airtime/index']) ?>' >

			  <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
              
              
			  <?=Html::img("@web/images/airtime.png", ["alt" => "loader","id"=>"", "class" => "dashicons" ]) ?>
            <div class="inner">
              <!--<h3>Air Time</h3>-->

              <p>Get up to 5% discount instantly when you purchase airtime.</p>
              Also you can sell airtime on our platform
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="<?=Url::to(['airtime/index']) ?>" class="small-box-footer">Buy/Sell <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
		  </a>
        <!-- ./col -->

		  <a href='<?=Url::to(['voucher/index']) ?>' >

			  <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
           
			   <?=Html::img("@web/images/moneyvoucher.jpg", ["alt" => "loader","id"=>"", "class" => "dashicons" ]) ?>
			  
            <div class="inner">
              <h3>Voucher</h3>

              <p>Buy/convert</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="<?=Url::to(['voucher/index']) ?>" class="small-box-footer">Buy Now <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
		  </a>
        <!-- ./col -->

		  <a href='<?=Url::to(['#']) ?>' class="bitcoin" >

			  <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
              
			  <?=Html::img("@web/images/opengraph.png", ["alt" => "loader","id"=>"", "class" => "dashicons dashiconheightlast" ]) ?>
            <div class="inner">
              <h3>Bit Coin</h3>

              <p>Buy/Sell Coming Soon...</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="<?=Url::to(['#']) ?>" class="small-box-footer bitcoin">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
		  </a>
        <!-- ./col -->
      </div>
	</section>
    
</div>

<? 
		Modal::begin([
			'header' =>'<h1 id="headers">Instructions</h1>',
			'id' => 'details',
			'size' => 'modal-md',  
		]);
?>
<div id="formcontent">
<div>You are expected to pay <em id="actualamount"></em></div>
<div>
<h4>Bank Details</h4>
<stong>Account Name </stong>Emeka Uchechukwu Michael<BR><HR/>
<stong>GTBANK</stong><em> 0215001020</em><BR><HR/>
<stong> ACCESS BANK</stong><em> 0042461814</em><BR><HR/>
<stong>FIRST BANK</stong><em> 3119596327</em><BR><HR/>
</div>
<div>
	<i>
		Please after payment send name of depositor, bank paid to and phone to receive the data to 09037072904 for confirmation ( if you paid with ATM or bank transfer code kindly indicate).
	</i>
</div>
</div>

<?
	Modal::end();
?>
<?
$contact = Yii::$app->user->identity->contacts->email;
$url = Url::to(['site/approve']);
$contactEmail = Url::to(['site/updatecontactemail']);
			 
$order = <<<JS

$('.bitcoin').click(function(e){
	e.preventDefault();
	alert ('Bitcoin option is presently not available');
	
});





JS;
 
$this->registerJs($order);

if(empty($contact)){

	$orderss = <<<JS
responce = prompt('Please Enter Email Address Below');
if(responce){
 
 $.ajax({
        	url: "$contactEmail"+"?id="+responce,
			type: "POST",
			
			success: function(data)
		    {
			alert ('Your email has been updated successfull');
		    },
		  	error: function() 
	    	{
	    	} 	        
	   });
}





JS;
 
$this->registerJs($orderss);

}
		
?>

frontend/views/dashboard/profile.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\grid\GridView;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dasgboard-index">

	<section class="content">
		<div class="row">
      		<!-- Small boxes (Stat box) -->
			<div class="col-sm-4">
			put the content here
				<table>
				<? foreach($userDetails as $k => $v){?>
				<tr>
					<td>
					</td>
					<td>
					</td>
				</tr>
				<? }?>
				</table>
			</div>
			<div class="col-sm-8">
			
				<?php $form = ActiveForm::begin(['id'=>'profile']); ?>

				<?= $form->field($personModel, 'first_name')->textInput() ?>

				<?= $form->field($personModel, 'last_name')->textInput() ?>

				<?= $form->field($personModel, 'account_number')->textInput() ?>
				<?= $form->field($contactModel, 'email')->textInput() ?>
				<?= $form->field($contactModel, 'phone_number')->textInput() ?>


				<div class="form-group">
					<?= Html::submitButton($personModel->isNewRecord ? 'Create' : 'Update', ['class' => $personModel->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
				</div>
			</div>
			

			<?php ActiveForm::end(); ?>
		</div>
	
	<h2>Fund wallet</h2>
	
	<div class="row">
		
		<div class="col-sm-4">
			content goes here 
		</div>
		<div class="col-sm-8">
		
      <!-- Small boxes (Stat box) -->
      	<?php $form = ActiveForm::begin(['id'=>'wallet']); ?>

		<?= $form->field($userModel, 'wallet')->textInput(['id'=>'wallets']) ?>

		
		

		<div class="form-group">
			<?= Html::submitButton($userModel->isNewRecord ? 'Fund' : 'Fund', ['class' => $userModel->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		</div>

		<?php ActiveForm::end(); ?>
	</div>
	
	</div>
</section>
    
</div>

<?
$profileUrl = Url::to(['dashboard/profilesave']);
$fundWalet = Url::to(['dashboard/fundwallet']);
$this->registerJsFile(
    'https://js.paystack.co/v1/inline.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
$backendIndexAjax = <<<JS

  
$('#profile').on('beforeSubmit', function (e) {
	$('#submitButtonTextpt').hide();
 	$('#BtnLoaderpt').show();
    var \$form = $(this);
	
	
	
	$.post('$profileUrl',\$form.serialize())
	.always(function(result){


		if(result.status==1){
			$('#BtnLoaderpt').hide();
			$(document).find('#feedbackpt').html('Sent').show();
		}else{
			$('#BtnLoaderpt').hide();
			$(document).find('#feedbackpt').html('Not enought funds in wallet').show();

		}
	}).fail(function(){
		console.log('Server Error');
	});
	 
    
	
	setTimeout(function(){ 
	$(document).find('#feedbackpt').hide();
	$(document).find('#BtnLoaderpt').hide();
	$(document).find('#submitButtonTextpt').show();
	$.pjax.reload({container:"#plan_type_pjax",async: false}); 
	}, 5000);
    return false;
 	
    
});

$('#wallet').on('beforeSubmit', function (e) {
	$('#submitButtonTextpt').hide();
 	$('#BtnLoaderpt').show();
    var \$form = $(this);
	
		
	
		var handler = PaystackPop.setup({
			
			  key: 'pk_live_60e06110fdefa3e025e94acf315c0baf26f2ca63',
			  email: 'kingsonly13c@gmail.com',
			  amount: $('#wallets').val()+'00',
			  
			  metadata: {
				 custom_fields: [
					{
						display_name: "Mobile Number",
						variable_name: "mobile_number",
						value: "+2348012345678"
					}
				 ]
			  },
			  callback: function(response){
				  
				  
				  $.post('$fundWalet',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
		alert('yes');
			  },
			  onClose: function(){
				  //alert('window closed');
			  }
		});
		handler.openIframe();
 
	
	
	
	setTimeout(function(){ 
	$(document).find('#feedbackpt').hide();
	$(document).find('#BtnLoaderpt').hide();
	$(document).find('#submitButtonTextpt').show();
	$.pjax.reload({container:"#plan_type_pjax",async: false}); 
	}, 5000);
    return false;
 	
    
});



JS;
 
$this->registerJs($backendIndexAjax);
?>