backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\BackendLoginForm;
use backend\models\BackendOrder;
use backend\models\BackendSellAirtime;
use backend\models\BackendPlanType;
use backend\models\BackendPlan;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','signup'],
                        'allow' => true,
                    ],
                    [
                        
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
		$modelPlanType = new \backend\models\BackendPlanType();
		$modelPlan = new \backend\models\BackendPlan();
		$findAllPlanType = $modelPlanType->find()->all();
		$findAllPlan = $modelPlan->find()->all();
        return $this->render('index',[
			'planTypeModel' => $modelPlanType,
			'planModel' => $modelPlan,
			'allPlanType' => $findAllPlanType,
			'allPlan' => $findAllPlan,
		]);
    }
	
	
	public function actionOrder()
    {
		$model = new BackendOrder();
		$pendingOrder = $model -> find()->where(['status'=>1,'administrator'=>Yii::$app->user->identity->id])->orWhere(['status'=>0,'administrator'=>Yii::$app->user->identity->id])->all();
		$approvedOrder = $model -> find()->where(['status'=>2,'administrator'=>Yii::$app->user->identity->id])->all();
        return $this->render('order',[
			'pendingOrder'=>$pendingOrder,
			'approvedOrder'=>$approvedOrder
		]);
    }
	
	public function actionAirtime()
    {
		$model = new BackendSellAirtime();
		$pendingOrder = $model -> find()->where(['status'=>1])->orWhere(['status'=>0])->all();
		$approvedOrder = $model -> find()->where(['status'=>2])->all();
        return $this->render('airtime',[
			'pendingOrder'=>$pendingOrder,
			'approvedOrder'=>$approvedOrder
		]);
    }
	
	public function actionOrderdetails($id)
    {
		$main = new BackendOrder();
		
		$model = $main->findAll($id);
		
        return $this->renderAjax('orderdetails',[
			'model' => $model
		]);
    }
	
	public function actionApprove($id)
    {
		$main = new BackendOrder();
		
		$model = $main->findOne($id);
		//$model = $main->find()->where(['order_id' => $id])->one();
		$model->status = 2;
		if($model->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="KINGSONLY";
			$subacctpwd="firstoctober";
			$sendto = !empty($model->contact->phone_number)?$model->contact->phone_number:'08083430800'; 
			$sender = 'BUYMB';
			$message = !empty($model->contact->phone_number)? 'Order has been confirmed':'Message was not sent to the contact cause contact does not have a number';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	public function actionApproveairtime($id)
    {
		$main = new BackendSellAirtime();
		
		$model = $main->findOne($id);
		//$model = $main->find()->where(['order_id' => $id])->one();
		$model->status = 2;
		if($model->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="BUYMB";
			$subacctpwd="firstoctober";
			$sendto = !empty($model->contact->phone_number)?$model->contact->phone_number:'08083430800'; 
			$sender = 'BUYMB';
			$message = !empty($model->contact->phone_number)? 'Thanks for your patronage , your order has been sent please dial *461*2# on mtn, *127*0# on glo *229*9# on 9m0bile and *140# on airtel to view data':'Message was not sent to the contact cause contact does not have a number';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	
	public function actionApproveairtimeorder($id)
    {
		$main = new BackendOrder();
		$mainAirtime = new BackendSellAirtime();
		
		
		$modelAirtime = $mainAirtime->findOne($id);
		$model = $main->find()->where(['airtime_id'=>$modelAirtime->sell_id])->one();
		
		$model->status = 1;
		$modelAirtime->status = 2;
		
		if($model->save(false) and $modelAirtime->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="BUYMB";
			$subacctpwd="firstoctober";
			$sendto = $model->contact->phone_number; 
			$sender = 'BUYMB';
			$message = 'Order has been confirmed';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	
	public function actionAirtimedetails($id)
    {
		$main = new BackendSellAirtime();
		
		$model = $main->findAll($id);
		
        return $this->renderAjax('airtimedetails',[
			'model' => $model
		]);
    }
	
	
    public function actionLogin()
    {
		$this->layout = 'loginsignup';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new BackendLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
	
	public function actionPlan()
	{
		$model = new \backend\models\BackendPlan();

			if ($model->load(Yii::$app->request->post())) {
			if ($model->validate()) {
				// save data
				$model->save();
				return 1;
			}
		} else{
			return 0;
		}
	}
	
	public function actionPlantype()
	{
		$model = new \backend\models\BackendPlanType();

		if ($model->load(Yii::$app->request->post())) {
			if ($model->validate()) {
				// save data
				$model->save();
				return 1;
			}
		} else{
			return 0;
		}

	}
	
	/*
	* this section contains code to update and delete all activities on the admindashboard
	*
	**/
	public function actionUpdatePlan($id){
		$model = BackendPlan::findOne($id);
		if($model->status == 1){
			$model->status = 0;
			if($model->save(false)){
				return 1;
			} else{
				return 0;
			}
		} else{
			$model->status = 1;
			if($model->save(false)){
				return 1;
			} else{
				return 0;
			}
		}
		
	}
	public function actionDeletePlan($id){
		$model = BackendPlan::findOne($id);
		if($model->delete()){
			return 1;
		} else{
			return 0;
		}
	}
	
	public function actionUpdatePlanType($id){
		$model = BackendPlanType::findOne($id);
		if($model->status_type == 1){
			$model->status_type = 0;
			if($model->save()){
				return 1;
			} else{
				return 0;
			}
		} else{
			$model->status_type = 1;
			if($model->save()){
				return 1;
			} else{
				return 0;
			}
		}
	}
	public function actionDeletePlanType($id){
		$model = BackendPlanType::findOne($id);
		if($model->delete()){
			return 1;
		} else{
			return 0;
		}
		
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
// Models 
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\PlanType;
use frontend\models\Order;
use frontend\models\Contact;
use frontend\models\Plan;
use frontend\models\UsersFeedback;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */


    /**
     * @inheritdoc
     */
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
	
	
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$this->layout = 'Site';
		// fetch all plantaype where type is  = data
		$planTypeDataModel = new PlanType();
		$dataModel = $planTypeDataModel->find()->where(['type'=>'data'])->andWhere(['status_type'=>0])->all();
		$airtimeModel = $planTypeDataModel->find()->where(['type'=>'airtime'])->all();
		$loginModel = new LoginForm();
		$signupModel = new SignupForm();
		
        return $this->render('index',[
			'dataType'=>$dataModel,
			'airtimeType'=>$airtimeModel,
			'model'=> new Order(),
			'contactModel'=> new Contact(),
			'loginModel'=> $loginModel,
			'signupModel'=> $signupModel,
			
		]);
    }
	
	public function actionGuest()
    {
		$this->layout = 'Site';
		// fetch all plantaype where type is  = data
		$model = new Order();
		$contactModel = new Contact();
		if (Yii::$app->user->isGuest) {
           $contactModel->scenario = $contactModel::SCENARIO_req;
        }
		
        return $this->renderAjax('orderform',[
			
			'model' => $model,
			'contactModel' => $contactModel,
		]);
		
    }
	

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		$this->layout = 'Login';
        
		
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
			//$dashboard = Url::to(['/dashboard/index']);
			return $this->redirect(['/dashboard/index']);
        } else{
			return $this->redirect(['/site/index']);
			
		}
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
		$this->layout = 'Site';
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
			$model->to = Yii::$app->params['adminEmail'];
			//$model->email = Yii::$app->params['adminEmail'];
            if ($model->sendEmail()) {
                return 1;
            } else {
                return 0;
            }

            
        } 
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
		$this->layout = 'Site';
        return $this->render('about');
    }
	
	public function actionUsersfeedback($mainId)
    {
		$model = new UsersFeedback();
		if ($model->load(Yii::$app->request->post()) && $model->sendEmail()) {
			return $model->hidden;
		} 
        return $this->renderAjax('_feedbackform',[
			'model'=>$model,
			'mainId'=>$mainId,
		]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
		$this->layout = 'Login';
        $model = new SignupForm();
        
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['dashboard/index']);;
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
		$this->layout = 'Login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
		$this->layout = 'Login';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
	
	public function actionUpdatecontactemail($id){
		$contactModelId = Yii::$app->user->identity->id;
		$contactModel = Contact::find()->where(['user_id'=>$contactModelId,'status'=>0])->one();
		if(!empty($contactModel)){
			$contactModel->email = $id;
		if($contactModel->save(false)){
			return true;
		}
		} else{
			$newContactModel = new Contact();
			$newContactModel -> user_id = $contactModelId;
			$newContactModel -> email = $id;
			
			
		}
		
		
	}
	
	public function actionActualamount($id){
		$planModel = Plan::findOne($id);
		$percentage = Yii::$app->params['rate'];
		$amount = $planModel->plan_amount;
		$getPer = ($percentage / 100) * $amount;
		$newAmount = $amount - $getPer;
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		return  $newAmount;
		
	}
	public function actionActualamountdata($id){
		$planModel = Plan::findOne($id);
		$amount = $planModel->plan_amount;
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		return $amount;
		
	}
	
}

backend/views/site/airtime.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
	#loaderspan{
		width: 40% !important;
		margin: 0 auto !important;
	}
	#formcontentsent{
		display:none;
	}
	.greens,.reds{
		width:100% !important;
		color: #fff;
	}
	.greens{
		background: green;
	}
	.reds{
		background: red;
	}
	#test{
		display: none;
	}
	.imgdivs{
		width: 40% !important;
		margin: 0 auto !important;
	}
</style>
<div class="dasgboard-index">

	<section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
		  <div class="col-sm-12 col-lg-6">
			  <div class="box" id = "project-title">
				  <div class="box-body" id = "project-title">
			  <table id="example1" class="table table-bordered table-striped">
							
                        	<thead>
                            <tr>
                              <th>SN</th>
                              <th>Network</th>
                              <th>Amount</th>
                              <th>Pin</th>
                              <th>Status</th>
                              <th>Action</th>
                  
                            </tr>
                        
							</thead>
                        	<tbody>
                            <? $sn=1; foreach($pendingOrder as $k=>$v){ ?>
								
                                <tr>
								
                                  <td class="projecturl"><?=$sn;?></td>
                                  <td class="projecturl"><?=$v['plantype']['network'];?></td>
                                  <td class="projecturl"><?=$v['amount'];?></td>
								<td class="projecturl"><?=$v['airtime_pin'];?></td>
                                  <td class="projecturl <?= $v['status'] <= 1?'danger':'success' ?>">
									  <?= $v['status'] <= 1?'Pending':'Approved' ?>
									</td>
                                  
									<td class="projecturl"><span data-id="<?=Url::to(['site/airtimedetails','id'=>$v["sell_id"]]) ?>" class="viewdetails btn">View</span></td>
                                </tr>
								
                            <? $sn++; }?>
                   
                  
							</tbody>
                        	<tfoot>
								<tr>
								  <th>SN</th>
                              <th>Network</th>
                              <th>Amount</th>
                              <th>Pin</th>
                              <th>Status</th>
                              <th>Action</th>

								</tr>
                			</tfoot>
                
                    
						</table>
				  </div>
			  </div>
		  </div>
		  
		  <div class="col-sm-12 col-lg-6"> 
			  <div class="box" id = "project-title">
				  <div class="box-body" id = "project-title">
			  	<table id="example1" class="table table-bordered table-striped">
							
                        	<thead>
                            <tr>
                              <th>SN</th>
                              <th>Network</th>
                              <th>Amount</th>
                              <th>Pin</th>
                              <th>Status</th>
                              <th>Action</th>
                  
                            </tr>
                        
							</thead>
                        	<tbody>
                            <? $sn=1; foreach($approvedOrder as $k=>$v){ ?>
								
                                 <tr>
								
                                  <td class="projecturl"><?=$sn;?></td>
                                  <td class="projecturl"><?=$v['plantype']['network'];?></td>
                                  <td class="projecturl"><?=$v['amount'];?></td>
								<td class="projecturl"><?=$v['airtime_pin'];?></td>
                                  <td class="projecturl <?= $v['status'] <= 1?'danger':'success' ?>">
									  <?= $v['status'] <= 1?'Pending':'Approved' ?>
									</td>
                                  
									<td class="projecturl"><span data-id="<?=Url::to(['site/airtimedetails','id'=>$v["sell_id"]]) ?>" class="viewdetails btn">View</span></td>
                                </tr>
								
                            <? $sn++; }?>
                   
                  
							</tbody>
                        	<tfoot>
								<tr>
								  <th>SN</th>
                              <th>Network</th>
                              <th>Amount</th>
                              <th>Pin</th>
                              <th>Status</th>
                              <th>Action</th>
									

								</tr>
                			</tfoot>
                
                    
						</table>
			  </div>
			  </div>
		  </div>
        <!-- ./col -->
      </div>
	</section>
    <? 
		Modal::begin([
			'header' =>'<h1 id="headers"></h1>',
			'id' => 'details',
			'size' => 'modal-md',  
		]);
?>
<div id="formcontent"></div>
<div id="formcontentsent"></div>
<?
	Modal::end();
?>
</div>

<?

$url = Url::to(['site/approveairtime']);
$order = <<<JS

$('.viewdetails').click(function(){
	
	var datas=$(this).data('id');
	$('.hideall').hide();
	$('#formcontentsent').hide();
	$('#formcontent').show();
	$('#details').modal('show').find('#formcontent').html('<div id="loaderspan"><img class="loadergif" src="../images/loader.gif"  /></div>');
	$('#details').modal('show').find('#formcontent').load(datas);
	
});

$(document).on('click','#approve',function(){
	id = $(this).data('id');
	$('#approvetxt').hide();
	$('#BtnLoaderp2').show();
	$('#BtnLoaderp').show();
	$.post('$url'+'?id='+id )
		.always(function(result){
	
			
   			
   			if(result==1){
	   			$('#BtnLoaderp2').hide();
	   			$('#BtnLoaderp').hide();
				$('#details').modal('show').find('#formcontent').hide();
				$('#details').modal('show').find('#formcontentsent').show();
	   			$('#details').find('#formcontentsent').html('<div class="imgdivs"><img class="imagess" src="../images/images.png"  /></div><br><h1>Request Have Been Approved</h1>').show().addClass('greens');
				
    		}else{
				$('#BtnLoader').hide();
				$('#details').modal('show').find('#formcontent').hide();
				$('#details').modal('show').find('#formcontentsent').show();
	   			$('#details').find('#formcontentsent').html('<div class="imgdivs"><img class="imagess" src="../images/images.png"  /><div><br><h1>An error occured</h1>').show().addClass('reds');
				
				
	
    		}
			
			
    	}).fail(function(){
    		console.log('Server Error');
    	});
		
		var countDownDate = new Date().getTime()+10000;

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
    
    // Find the distance between now an the count down date
    var distance = countDownDate - now;
    
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";
    
    // If the count down is over, write some text 
    if (distance < 0) {
        clearInterval(x);
        
    
		
		
		
	$('#details').modal().find('#formcontent').show();
	$('#details').modal().find('#formcontentsent').hide();
	$('#approvetxt').show();
	$(document).find('#submitButtonText').show();
	$('#details').modal('hide');
	$('#test').show();
	 function Particle( x, y, radius ) {
            this.init( x, y, radius );
        }

        Particle.prototype = {

            init: function( x, y, radius ) {

                this.alive = true;

                this.radius = radius || 10;
                this.wander = 0.15;
                this.theta = random( TWO_PI );
                this.drag = 0.92;
                this.color = '#fff';

                this.x = x || 0.0;
                this.y = y || 0.0;

                this.vx = 0.0;
                this.vy = 0.0;
            },

            move: function() {

                this.x += this.vx;
                this.y += this.vy;

                this.vx *= this.drag;
                this.vy *= this.drag;

                this.theta += random( -0.5, 0.5 ) * this.wander;
                this.vx += sin( this.theta ) * 0.1;
                this.vy += cos( this.theta ) * 0.1;

                this.radius *= 0.96;
                this.alive = this.radius > 0.5;
            },

            draw: function( ctx ) {

                ctx.beginPath();
                ctx.arc( this.x, this.y, this.radius, 0, TWO_PI );
                ctx.fillStyle = this.color;
                ctx.fill();
            }
        };

        // ----------------------------------------
        // Example
        // ----------------------------------------

        var MAX_PARTICLES = 280;
        var COLOURS = [ '#69D2E7', '#A7DBD8', '#E0E4CC', '#F38630', '#FA6900', '#FF4E50', '#F9D423' ];

        var particles = [];
        var pool = [];

        var demo = Sketch.create({
            container: document.getElementById( 'test' ),
            retina: 'auto'
        });

        demo.setup = function() {

            // Set off some initial particles.
            var i, x, y;

            for ( i = 0; i < 100; i++ ) {
                x = ( demo.width * 0.5 ) + random( -100, 100 );
                y = ( demo.height * 0.5 ) + random( -100, 100 );
                demo.spawn( x, y );
            }
        };

        demo.spawn = function( x, y ) {
            
            var particle, theta, force;

            if ( particles.length >= MAX_PARTICLES )
                pool.push( particles.shift() );

            particle = pool.length ? pool.pop() : new Particle();
            particle.init( x, y, random( 5, 40 ) );

            particle.wander = random( 0.5, 2.0 );
            particle.color = random( COLOURS );
            particle.drag = random( 0.9, 0.99 );

            theta = random( TWO_PI );
            force = random( 2, 8 );

            particle.vx = sin( theta ) * force;
            particle.vy = cos( theta ) * force;

            particles.push( particle );
        };

        demo.update = function() {

            var i, particle;

            for ( i = particles.length - 1; i >= 0; i-- ) {

                particle = particles[i];

                if ( particle.alive ) particle.move();
                else pool.push( particles.splice( i, 1 )[0] );
            }
        };

        demo.draw = function() {

            demo.globalCompositeOperation  = 'lighter';

            for ( var i = particles.length - 1; i >= 0; i-- ) {
                particles[i].draw( demo );
            }
        };
		
	$.pjax.reload({container:"#order_approved",async: false}); 
	$.pjax.reload({container:"#order_pending",async: false}); 
	$(".order1").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });
	
	$(".order2").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });
	$('#test').delay(1000).hide(0);
	
	//}, 5000);
	}
}, 1000);
    return false;
});



$(".table").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });
	
	$(".order2").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });


JS;
 
$this->registerJs($order);
?>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>