frontend/controllers/DataController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Json;

// Models 
use frontend\models\Order;
use frontend\models\Plan;
use frontend\models\Contact;



/**
 * Site controller
 */
class DataController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$model = new Order();
		$contactModel = new Contact();
		$contactModel->scenario = $contactModel::SCENARIO_DATA;
		$myOrder = $model->find()->where(['user_id'=> Yii::$app->user->identity->id,'order_type'=>'data'])->all();
        return $this->render('index',[
			'myOrder' => $myOrder,
			'model' => $model,
			'contactModel' => $contactModel,
		]);
    }
	
	public function actionListItems() 
	{
    	$result = [];
		$post = Yii::$app->request->post('Order');
		$parents = $_POST['depdrop_parents'];
		
		$result = Plan::find()->where(['plan_type_id'=>$parents[0]])->select(['plan_id As id','plan_name   As name'])->asArray()->all();
		
		return Json::encode(['output'=>$result, 'selected'=>'1000']);  
		
		
		
		
		
		
    	//echo Json::encode(['output'=>'', 'selected'=>'']);
	}
	

  
}

frontend/views/data/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Plan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="plan-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'plan_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'plan_amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'plan_type_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?
$this->registerJsFile(
    'https://js.paystack.co/v1/inline.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
$voucheUrl = Url::to(['order/paymentwithvoucher']);
$walletUrl = Url::to(['order/paymentwithwallet']);
$cardValidationUrl = Url::to(['order/paymentwithcardvalidation']);
$cashAprovedUrl = Url::to(['order/paymentwithcarddata']);

$order = <<<JS

$('#paymentmode').change(function(){
	value = $(this).val();
	if(value == 'voucher'){
		$('#voucher').show();
	} else{
		$('#voucher').hide();
	}
});


$('#dataform').on('beforeSubmit', function (e) {
	$('#submitButtonText').hide();
 	$('#BtnLoader').show();
    var \$form = $(this);
	var planid = $('#plan_id').val();
	var paymentMode = $('#paymentmode').val();
	
	function payWithPaystack(customerEmail,amount,createOrder){
		var handler = PaystackPop.setup({
			
			  key: 'pk_test_9fffdfb13c6194a5a236b933ddb00aa29a78dd78',
			  email: customerEmail,
			  amount: amount+'00',
			  
			  metadata: {
				 custom_fields: [
					{
						display_name: "Mobile Number",
						variable_name: "mobile_number",
						value: "+2348012345678"
					}
				 ]
			  },
			  callback: function(response){
				  
				  
				  $.post('$cashAprovedUrl'+'?amountid='+$('#plan_id').val()+'& ordertype=airtime',$('#dataform').serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
		alert('yes');
			  },
			  onClose: function(){
				  //alert('window closed');
			  }
		});
		handler.openIframe();
  }
  
  
  function createOrder(planid){
		$.post('$cashAprovedUrl'+'?amountid='+planid+'& ordertype=airtime',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	}
	
	if(paymentMode == 'wallet'){
		$.post('$walletUrl'+'?amountid='+planid+'& ordertype=airtime',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if (paymentMode == 'card'){
	
		$.post('$cardValidationUrl'+'?amountid='+planid,\$form.serialize())
		.always(function(result){
	
			
   			if(result.success==1){
				
				customerEmail = result.email;
				if(customerEmail.lenght == 0){
				 customerEmail = 'kingsonly13c@gmail.com';
				}
				
				payWithPaystack(customerEmail,result.amount,createOrder);
	   			
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if (paymentMode == 'voucher'){
			var pin = $('#voucher').val();
			$.post('$voucheUrl'+'?pin='+pin+'& amountid='+planid+'& ordertype=airtime',\$form.serialize())
		.always(function(result){
	
			$(document).find('#loader').hide();
   			if(result==1){
			$('#BtnLoader').hide();
	   
	   			$(document).find('#feedback').html('sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Voucher used or Voucher is not correct').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else{
		alert('no option selected');
	}
    
	
	setTimeout(function(){ 
	$(document).find('#feedback').hide();
	$(document).find('#BtnLoader').hide();
	$(document).find('#submitButtonText').show();
	
		$.pjax.reload({container:"#buy_airtime",async: false}); 
	}, 5000);
    return false;
 	
    
});


JS;
 
$this->registerJs($order);
?>

frontend/views/data/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\grid\GridView;
use yii\bootstrap\Modal;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dasgboard-index">
	<h1 style="padding:0px 15px;">
		Buy Data
	</h1>

	<section class="content">
      <!-- Small boxes (Stat box) -->
		
      <div class="row">
		  <div class="col-sm-12 col-lg-6">
			  <?= $this->render('orderform', [
				'model' => $model,
				'contactModel' => $contactModel,
			]) ?>
		  </div>
		  
		  <div class="col-sm-12 col-lg-6"> 
			  <div class="box" id = "project-title">
				  <div class="box-body" id = "project-title">
					  <?php Pjax::begin(['id' => 'buy_data']) ?>
			  	<table id="example1" class="table table-bordered table-striped">
							
                        	<thead>
                            <tr>
                              <th>SN</th>
                              <th>Plan</th>
                              <th>Payment Option</th>
                              <th>Status</th>
                              <th>Date</th>
                  
                            </tr>
                        
							</thead>
                        	<tbody>
                            <? $sn=1; foreach($myOrder as $k=>$v){ ?>
								
                                <tr>
								
                                  <td class="projecturl"><?=$sn;?></td>
                                  <td class="projecturl"><?=$v['plan']['plan_name'].' ('.$v['plan']['plan_amount'].')';?></td>
                                  <td class="projecturl"><?=$v['payment_mode'];?></td>
                                  <td class="projecturl <?= $v['status'] == 1?'danger':'success' ?>">
									  <?= $v['status'] == 1?'Pending':'Approved' ?>
									</td>
                                  <td class="projecturl"><?=$v['date_created'];?></td>

                                </tr>
								
                            <? $sn++; }?>
                   
                  
							</tbody>
                        	<tfoot>
								<tr>
								  <th>SN</th>
								  <th>Plan</th>
								  <th>Payment Option</th>
								  <th>Status</th>
								  <th>Date</th>

								</tr>
                			</tfoot>
                
                    
						</table>
					  <?php Pjax::end() ?>
			  </div>
			  </div>
		  </div>
        <!-- ./col -->
      </div>
	</section>
    
</div>

<? 
		Modal::begin([
			'header' =>'<h1 id="headers">Instructions</h1>',
			'id' => 'details',
			'size' => 'modal-md',  
		]);
?>
<div id="formcontent">
<div>You are expected to pay <em id="actualamount"></em></div>
<div>
<h4>Bank Details</h4>
<stong>Account Name </stong>Emeka Uchechukwu Michael<BR><HR/>
<stong>GTBANK</stong><em> 0215001020</em><BR><HR/>
<stong> ACCESS BANK</stong><em> 0042461814</em><BR><HR/>
<stong>FIRST BANK</stong><em> 3119596327</em><BR><HR/>
</div>
<div>
	<i>
		Please after payment send name of depositor, bank paid to , to 09037072904 for confirmation ( if you paid with ATM or bank transfer code kindly indicate).
	</i>
</div>
</div>

<?
	Modal::end();
?>



<?

			 
$order3 = <<<JS
 $("#example1").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });


JS;
 $this->registerJs($order3);

		
?>

frontend/views/data/orderform.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use frontend\models\planType;

use kartik\depdrop\DepDrop;

/* @var $this yii\web\View */
/* @var $model app\models\order */
/* @var $form ActiveForm */
?>

<style>
	#voucher{
		display: none;
		margin-bottom: 10px;
	}
	#numbers{
		display: none;
		
	}
	#BtnLoader{
		display:none;
	}
	
</style>
<div class="data-orderform">

    <?php $form = ActiveForm::begin(['action' =>['folder/create'],'id'=>'dataform']); ?>
	
		<?= $form->field($model, 'plan_id_selector')->dropDownList(ArrayHelper::map(planType::find()->where(['type'=>'data'])->all(), 'type_id', 'network'),[ 'prompt'=> 'Select...', 'class' => 'form-control', 'id' => 'plantype']) ?>
    
	
		<?= $form->field($model, 'plan_id')->widget(DepDrop::classname(), [
			'options'=>['id' => 'plan_id',"data-toggle" => "popover","data-placement" => "top", "data-trigger" => "change", "data-content" => "Change content to view amount to pay"],
			'pluginOptions' => [
				'depends' => ['plantype'],
				'placeholder' => 'Select...',
				
				'url'=>Url::to(['/data/list-items'])
			]
		]);
		?>
	
        <? $payment = ['card'=>'Card','voucher'=>'Voucher','wallet'=>'Wallet','transfer'=>'Bank Transfer'] ?>
		
		
		Buy for a friend <input type="checkbox" value="1" name="friend" id="buyfriend" />
	<div id="numbers">
			<?= $form->field($contactModel, 'phone_number')->textInput(['id'=>'phone_number'])->label('Enter Friend Phone Number') ?>
		</div>
	
		<?= $form->field($model, 'payment_mode')->dropDownList($payment,[ 'prompt'=> 'Select...', 'class' => 'form-control', 'id' => 'paymentmode']) ?>
	<div id="voucher">
		<label  class="control-label">Enter Voucher</label>
		<input type="text" class="form-control" id='pin'/>
	</div>
		
	
        
    
        <div class="form-group">
            <? //= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
			<?= Html::submitButton($model->isNewRecord ? '<span id="submitButtonText">Submit</span>'.Html::img("@web/images/45.gif", ["alt" => "loader","id"=>"BtnLoader", "class" => "user-image23" ]).' <span id="feedback"><span>' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-basic' : 'btn btn-basic','id'=>'submitbtn']) ?>

        </div>
    <?php ActiveForm::end(); ?>
	
	
</div><!-- data-orderform -->
<?
$voucheUrl = Url::to(['order/paymentwithvoucher']);
$walletUrl = Url::to(['order/paymentwithwallet']);
$cardValidationUrl = Url::to(['order/paymentwithcardvalidation']);
$cashAprovedUrl = Url::to(['order/paymentwithcarddata']);
$transferUrl = Url::to(['order/paymentbytransfer']);
$actualAmountUrl = Url::to(['site/actualamountdata']);

$this->registerJsFile(
    'https://js.paystack.co/v1/inline.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
$order = <<<JS


	
$('[data-toggle="popover"]').popover(); 

$('#paymentmode').change(function(){
	value = $(this).val();
	if(value == 'voucher'){
		$('#voucher').show();
	} else{
		$('#voucher').hide();
	}
});


$('#plan_id').change(function(){
	planid = $(this).val();
	currentValue = $(this);
	language = 0;
	$.post('$actualAmountUrl'+'?id='+planid)
		.always(function(actualAmount){
	
			
   			if(actualAmount >= 1){
				
				currentValue.attr('data-content','you are to pay '+actualAmount+' Naira for this plan');
				 currentValue.popover('show');
				}else{
			
				currentValue.attr('data-content','could not fetch amount.');
				 currentValue.popover('show');
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
   

});



$('#buyfriend').click(function(){
	value = $(this).checked;
	if($(this).is(":checked")){
		$('#numbers').show();
	} else{
		$('#numbers').hide();
	}
});

function payWithPaystackfake(test){
		alert(test);
  }
  
$('#dataform').on('beforeSubmit', function (e) {

	$('#submitButtonText').hide();
 	$('#BtnLoader').show();
    var \$form = $(this);
	var planid = $('#plan_id').val();
	var paymentMode = $('#paymentmode').val();
	
	function payWithPaystack(customerEmail,amount,createOrder){
		var handler = PaystackPop.setup({
			
			  key: 'pk_live_60e06110fdefa3e025e94acf315c0baf26f2ca63',
			  email: customerEmail,
			  amount: amount+'00',
			  
			  metadata: {
				 custom_fields: [
					{
						display_name: "Mobile Number",
						variable_name: "mobile_number",
						value: "+2348012345678"
					}
				 ]
			  },
			  callback: function(response){
				  
				  
				  $.post('$cashAprovedUrl'+'?amountid='+$('#plan_id').val()+'& ordertype=data',$('#dataform').serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
		alert('yes');
			  },
			  onClose: function(){
				  //alert('window closed');
			  }
		});
		handler.openIframe();
  }
  
	
	function createOrder(planid){
		$.post('$cashAprovedUrl'+'?amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	}
	
	
	
	var mainActualAmount = 0;
	$.post('$actualAmountUrl'+'?id='+planid)
		.always(function(actualAmount){
	
			
   			if(actualAmount >= 1){
			mainActualAmount = actualAmount;
				}else{
			
				alert('Could not fetch actual amount');
				return false;
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
		
	   			
				if(paymentMode == 'wallet'){
		$.post('$walletUrl'+'?amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if(paymentMode == 'transfer'){
	
		$.post('$transferUrl'+'?amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
	   			
	   			$(document).find('#successTransfer').slideDown();
				
				$('#details').modal('show').find('#actualamount').html(mainActualAmount);
				
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('An Error occured pls try again').show();
				$(document).find('#formcontent').slideUp();
	   			$(document).find('#successTransfer').slideDown();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	}else if (paymentMode == 'card'){
		$.post('$cardValidationUrl'+'?amountid='+planid,\$form.serialize())
		.always(function(result){
	
			
   			if(result.success==1){
				
				customerEmail = result.email;
				if(customerEmail.lenght == 0){
				 customerEmail = 'kingsonly13c@gmail.com';
				}
				
				payWithPaystack(customerEmail,result.amount,createOrder);
	   			
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if (paymentMode == 'voucher'){
			var pin = $('#pin').val();
			$.post('$voucheUrl'+'?pin='+pin+'& amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			$(document).find('#loader').hide();
   			if(result==1){
			$('#BtnLoader').hide();
	   
	   			$(document).find('#feedback').html('sent').show();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Invalid or Pin used').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else{
		alert('no option selected');
	}
    
	
	setTimeout(function(){ 
	$(document).find('#feedback').hide();
	$(document).find('#BtnLoader').hide();
	$(document).find('#submitButtonText').show();
	$.pjax.reload({container:"#buy_data",async: false}); 
	$("#example1").DataTable({
        "aaSorting": [],
		"pagingType": "simple",
		"responsive": "true",
		
    });
	}, 5000);
    return false;
				
				
    	
	
	
	
	
	
 	
    
});


JS;
 
$this->registerJs($order);
?>