backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\BackendLoginForm;
use backend\models\BackendOrder;
use backend\models\BackendSellAirtime;
use backend\models\BackendPlanType;
use backend\models\BackendPlan;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','signup'],
                        'allow' => true,
                    ],
                    [
                        
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
		$modelPlanType = new \backend\models\BackendPlanType();
		$modelPlan = new \backend\models\BackendPlan();
		$findAllPlanType = $modelPlanType->find()->all();
		$findAllPlan = $modelPlan->find()->all();
        return $this->render('index',[
			'planTypeModel' => $modelPlanType,
			'planModel' => $modelPlan,
			'allPlanType' => $findAllPlanType,
			'allPlan' => $findAllPlan,
		]);
    }
	
	
	public function actionOrder()
    {
		$model = new BackendOrder();
		$pendingOrder = $model -> find()->where(['status'=>1,'administrator'=>Yii::$app->user->identity->id])->orWhere(['status'=>0,'administrator'=>Yii::$app->user->identity->id])->all();
		$approvedOrder = $model -> find()->where(['status'=>2,'administrator'=>Yii::$app->user->identity->id])->all();
        return $this->render('order',[
			'pendingOrder'=>$pendingOrder,
			'approvedOrder'=>$approvedOrder
		]);
    }
	
	public function actionAirtime()
    {
		$model = new BackendSellAirtime();
		$pendingOrder = $model -> find()->where(['status'=>1])->orWhere(['status'=>0])->all();
		$approvedOrder = $model -> find()->where(['status'=>2])->all();
        return $this->render('airtime',[
			'pendingOrder'=>$pendingOrder,
			'approvedOrder'=>$approvedOrder
		]);
    }
	
	public function actionOrderdetails($id)
    {
		$main = new BackendOrder();
		
		$model = $main->findAll($id);
		
        return $this->renderAjax('orderdetails',[
			'model' => $model
		]);
    }
	
	public function actionApprove($id)
    {
		$main = new BackendOrder();
		
		$model = $main->findOne($id);
		//$model = $main->find()->where(['order_id' => $id])->one();
		$model->status = 2;
		if($model->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="KINGSONLY";
			$subacctpwd="firstoctober";
			$sendto = !empty($model->contact->phone_number)?$model->contact->phone_number:'08083430800'; 
			$sender = 'BUYMB';
			$message = !empty($model->contact->phone_number)? 'Order has been confirmed':'Message was not sent to the contact cause contact does not have a number';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	public function actionApproveairtime($id)
    {
		$main = new BackendSellAirtime();
		
		$model = $main->findOne($id);
		//$model = $main->find()->where(['order_id' => $id])->one();
		$model->status = 2;
		if($model->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="BUYMB";
			$subacctpwd="firstoctober";
			$sendto = !empty($model->contact->phone_number)?$model->contact->phone_number:'08083430800'; 
			$sender = 'BUYMB';
			$message = !empty($model->contact->phone_number)? 'Thanks for your patronage , your order has been sent please dial *461*2# on mtn, *127*0# on glo *229*9# on 9m0bile and *140# on airtel to view data':'Message was not sent to the contact cause contact does not have a number';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	
	public function actionApproveairtimeorder($id)
    {
		$main = new BackendOrder();
		$mainAirtime = new BackendSellAirtime();
		
		
		$modelAirtime = $mainAirtime->findOne($id);
		$model = $main->find()->where(['airtime_id'=>$modelAirtime->sell_id])->one();
		
		$model->status = 1;
		$modelAirtime->status = 2;
		
		if($model->save(false) and $modelAirtime->save(false)){
			$owneremail="kingsonly13c@gmail.com";
			$subacct="BUYMB";
			$subacctpwd="firstoctober";
			$sendto = $model->contact->phone_number; 
			$sender = 'BUYMB';
			$message = 'Order has been confirmed';
			$model->smsModel($owneremail,$subacct,$subacctpwd,$sendto,$sender,$message);
			$data = 1;
		} else {
			$data = 2;
		}
		
        return $data;
    }
	
	public function actionAirtimedetails($id)
    {
		$main = new BackendSellAirtime();
		
		$model = $main->findAll($id);
		
        return $this->renderAjax('airtimedetails',[
			'model' => $model
		]);
    }
	
	
    public function actionLogin()
    {
		$this->layout = 'loginsignup';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new BackendLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
	
	public function actionPlan()
	{
		$model = new \backend\models\BackendPlan();

			if ($model->load(Yii::$app->request->post())) {
			if ($model->validate()) {
				// save data
				$model->save();
				return 1;
			}
		} else{
			return 0;
		}
	}
	
	public function actionPlantype()
	{
		$model = new \backend\models\BackendPlanType();

		if ($model->load(Yii::$app->request->post())) {
			if ($model->validate()) {
				// save data
				$model->save();
				return 1;
			}
		} else{
			return 0;
		}

	}
	
	/*
	* this section contains code to update and delete all activities on the admindashboard
	*
	**/
	public function actionUpdatePlan($id){
		$model = BackendPlan::findOne($id);
		if($model->status == 1){
			$model->status = 0;
			if($model->save(false)){
				return 1;
			} else{
				return 0;
			}
		} else{
			$model->status = 1;
			if($model->save(false)){
				return 1;
			} else{
				return 0;
			}
		}
		
	}
	public function actionDeletePlan($id){
		$model = BackendPlan::findOne($id);
		if($model->delete()){
			return 1;
		} else{
			return 0;
		}
	}
	
	public function actionUpdatePlanType($id){
		$model = BackendPlanType::findOne($id);
		if($model->status_type == 1){
			$model->status_type = 0;
			if($model->save()){
				return 1;
			} else{
				return 0;
			}
		} else{
			$model->status_type = 1;
			if($model->save()){
				return 1;
			} else{
				return 0;
			}
		}
	}
	public function actionDeletePlanType($id){
		$model = BackendPlanType::findOne($id);
		if($model->delete()){
			return 1;
		} else{
			return 0;
		}
		
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
// Models 
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\PlanType;
use frontend\models\Order;
use frontend\models\Contact;
use frontend\models\Plan;
use frontend\models\UsersFeedback;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */


    /**
     * @inheritdoc
     */
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
	
	
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$this->layout = 'Site';
		// fetch all plantaype where type is  = data
		$planTypeDataModel = new PlanType();
		$dataModel = $planTypeDataModel->find()->where(['type'=>'data'])->andWhere(['status_type'=>0])->all();
		$airtimeModel = $planTypeDataModel->find()->where(['type'=>'airtime'])->all();
		$loginModel = new LoginForm();
		$signupModel = new SignupForm();
		
        return $this->render('index',[
			'dataType'=>$dataModel,
			'airtimeType'=>$airtimeModel,
			'model'=> new Order(),
			'contactModel'=> new Contact(),
			'loginModel'=> $loginModel,
			'signupModel'=> $signupModel,
			
		]);
    }
	
	public function actionGuest()
    {
		$this->layout = 'Site';
		// fetch all plantaype where type is  = data
		$model = new Order();
		$contactModel = new Contact();
		if (Yii::$app->user->isGuest) {
           $contactModel->scenario = $contactModel::SCENARIO_req;
        }
		
        return $this->renderAjax('orderform',[
			
			'model' => $model,
			'contactModel' => $contactModel,
		]);
		
    }
	

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		$this->layout = 'Login';
        
		
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
			//$dashboard = Url::to(['/dashboard/index']);
			return $this->redirect(['/dashboard/index']);
        } else{
			return $this->redirect(['/site/index']);
			
		}
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
		$this->layout = 'Site';
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
			$model->to = Yii::$app->params['adminEmail'];
			//$model->email = Yii::$app->params['adminEmail'];
            if ($model->sendEmail()) {
                return 1;
            } else {
                return 0;
            }

            
        } 
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
		$this->layout = 'Site';
        return $this->render('about');
    }
	
	public function actionUsersfeedback($mainId)
    {
		$model = new UsersFeedback();
		if ($model->load(Yii::$app->request->post()) && $model->sendEmail()) {
			return $model->hidden;
		} 
        return $this->renderAjax('_feedbackform',[
			'model'=>$model,
			'mainId'=>$mainId,
		]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
		$this->layout = 'Login';
        $model = new SignupForm();
        
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['dashboard/index']);;
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
		$this->layout = 'Login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
		$this->layout = 'Login';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
	
	public function actionUpdatecontactemail($id){
		$contactModelId = Yii::$app->user->identity->id;
		$contactModel = Contact::find()->where(['user_id'=>$contactModelId,'status'=>0])->one();
		if(!empty($contactModel)){
			$contactModel->email = $id;
		if($contactModel->save(false)){
			return true;
		}
		} else{
			$newContactModel = new Contact();
			$newContactModel -> user_id = $contactModelId;
			$newContactModel -> email = $id;
			
			
		}
		
		
	}
	
	public function actionActualamount($id){
		$planModel = Plan::findOne($id);
		$percentage = Yii::$app->params['rate'];
		$amount = $planModel->plan_amount;
		$getPer = ($percentage / 100) * $amount;
		$newAmount = $amount - $getPer;
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		return  $newAmount;
		
	}
	public function actionActualamountdata($id){
		$planModel = Plan::findOne($id);
		$amount = $planModel->plan_amount;
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		return $amount;
		
	}
	
}

frontend/views/site/_feedbackform.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\rating\StarRating;

/* @var $this yii\web\View */
/* @var $model app\models\Rate */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
	.btnloading,.btnsent{
		display:none;
		color:#fff !important;
	}
</style>
<div class="rate-form">
<h2 style="text-align:center"> We love feedback </h2>
    <?php $form = ActiveForm::begin(['id'=>'feedbackform'.$mainId]); ?>

    <?= $form->field($model, 'email')->textInput() ?>
    <?= $form->field($model, 'hidden')->hiddenInput(['id'=>'hiden'])->label(false) ?>
    <?= $form->field($model, 'startRating')->widget(StarRating::classname(), [
        'pluginOptions' => [
		
        'min' => 0,
        'max' => 12,
        'step' => 2,
        'size' => 'lg',
        'starCaptions' => [
            0 => 'Extremely Poor',
            2 => 'Very Poor',
            4 => 'Poor',
            6 => 'Ok',
            8 => 'Good',
            10 => 'Very Good',
            12 => 'Extremely Good',
        ],
        'starCaptionClasses' => [
            0 => 'text-danger',
            2 => 'text-danger',
            4 => 'text-warning',
            6 => 'text-info',
            8 => 'text-primary',
            10 => 'text-success',
            12 => 'text-success'
        ],
    ],
	'options' => [
	'id' => 'feedbackinput'.$mainId,
]
]);
 ?>
    <?= $form->field($model, 'body')->textarea(['rows' => '6']) ?>

    <div class="form-group">
        <?= Html::submitButton('<span class="btnnormal">Send<span><span class="btnloading" >Loading .......<span> <span class="btnsent">Sent<span>', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?
$url = Url::to(['site/usersfeedback']);
$order = <<<JS
$('#feedbackform'+$mainId).on('beforeSubmit', function (e) {
	$(document).find('.btnnormal').hide();
	$(document).find('.btnloading').show();
	
	$('#submitButtonText').hide();
 	$('#BtnLoader').show();
    var \$form = $(this);
	var customermail = \$form.find('.customer_email').val();
	var planid = $('#plan_id').val();
	var paymentMode = $('#paymentmode').val();	
	$.post(\$form.attr('action'),\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
				$(document).find('.btnloading').hide();
				$(document).find('.btnsent').show();
	   			$('.formcontentotherfeedback').hide();
	   			$('.cardthanks').show();
				\$form.parent().parent().parent().parent().find('.cardthanks').show();
				
					$('#test1').load(' #test1');
					$('#test2').load(' #test2');
					$('#test3').load(' #test3');
					$('#firstcart3').load(' #firstcart3');
					$('#firstcart2').load(' #firstcart2');
					$('#firstcart').load(' #firstcart');
    		}else{
				$(document).find('.btnloading').hide();
				$(document).find('.btnsent').show();
				$('.formcontentotherfeedback').hide();
				\$form.parent().parent().parent().parent().find('.formcontenttransferfeedback').show();
				
					$('#test1').load(' #test1');
					$('#test2').load(' #test2');
					$('#test3').load(' #test3');
					$('#firstcart3').load(' #firstcart3');
					$('#firstcart2').load(' #firstcart2');
					$('#firstcart').load(' #firstcart');
				
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	
    
	
	
    return false;
 	
    
});


JS;
 
$this->registerJs($order);
?>

frontend/views/site/guestorder.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use frontend\models\planType;

use kartik\depdrop\DepDrop;

/* @var $this yii\web\View */
/* @var $model app\models\order */
/* @var $form ActiveForm */
?>

<style>
	<? 
if (!Yii::$app->user->isGuest) {
           
        
?>
	
	#numbers{
		display: none;
		
	}
	
<? }?>
	#voucher{
		display: none;
		margin-bottom: 10px;
	}
	#BtnLoader{
		display:none;
	}
</style>
<div class="data-orderform">

    <?php $form = ActiveForm::begin(['action' =>['folder/create'],'id'=>'dataforms']); ?>
	
        <? if (!Yii::$app->user->isGuest) {
				$payment = ['card'=>'ATM Card','voucher'=>'Voucher','wallet'=>'Wallet','transfer'=>'Bank Transfer'];
			}else{
				$payment = ['card'=>'ATM Card','voucher'=>'Voucher','transfer'=>'Bank Transfer'];
			}
	?>
	
        
		
		
	
	
		<?= $form->field($model, 'payment_mode')->dropDownList($payment,[ 'prompt'=> 'Select...', 'class' => 'form-control', 'id' => 'paymentmode']) ?>
	
	<div id="voucher">
		<label  class="control-label">Enter Voucher</label>
		<input type="text" class="form-control" id='pin'/>
	</div>
		
	
        
    <?= $form->field($model, 'customer_email')->textInput(['class'=>'customer_email']);
		?>
        <div class="form-group">
            <? //= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
			<?= Html::submitButton($model->isNewRecord ? '<span id="submitButtonText">Submit</span>'.Html::img("@web/images/45.gif", ["alt" => "loader","id"=>"BtnLoader", "class" => "user-image23" ]).' <span id="feedback"><span>' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-basic' : 'btn btn-basic','id'=>'submitbtn']) ?>

        </div>
    <?php ActiveForm::end(); ?>
	
	
</div><!-- data-orderform -->
<?
$voucheUrl = Url::to(['order/bulk-paymentwithvoucher']);
$walletUrl = Url::to(['order/paymentwithwallet']);
$cardValidationUrl = Url::to(['order/bulk-paymentwithcardvalidation']);
$cashAprovedUrl = Url::to(['order/bulkpaymentwithcarddata']);
$transferUrl = Url::to(['order/bulk-paymentbytransfer']);
$actualAmountUrl = Url::to(['site/actualamountdata']);
$feedbackUrl = Url::to(['site/usersfeedback','mainId'=>1]);
$actualAmountUrlmain = \Yii::$app->cart->getCost();

$this->registerJsFile(
    'https://js.paystack.co/v1/inline.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
$order = <<<JS
$('#formcontentotherfeedback1').load('$feedbackUrl');
$('#paymentmode').change(function(){

	value = $(this).val();
	
	if(value == 'voucher'){
		$('#voucher').show();
	} else{
		$('#voucher').hide();
	}
});

$('#buyfriend').click(function(){
	value = $(this).checked;
	if($(this).is(":checked")){
		$('#numbers').show();
	} else{
		$('#numbers').hide();
	}
});


  
$('#dataforms').on('beforeSubmit', function (e) {
	$('#submitButtonText').hide();
 	$('#BtnLoader').show();
    var \$form = $(this);
	var customermail = \$form.find('.customer_email').val();
	var planid = $('#plan_id').val();
	var paymentMode = $('#paymentmode').val();
	
	
	
	
	function payWithPaystack(customerEmail,amount,createOrder){
	
		var handler = PaystackPop.setup({
			
			 // key: 'pk_live_60e06110fdefa3e025e94acf315c0baf26f2ca63',
			  key: 'pk_test_9fffdfb13c6194a5a236b933ddb00aa29a78dd78',
			  email: customermail,
			  amount: amount+'00',
			  
			  metadata: {
				 custom_fields: [
					{
						display_name: "Mobile Number",
						variable_name: "mobile_number",
						value: "+2348012345678"
					}
				 ]
			  },
			  callback: function(response){
				  
				  
				  $.post('$cashAprovedUrl'+'?ordertype=data',$('#dataform').serialize())
		.always(function(result){
	
			
   			if(result==1){
			 \$form.parent().parent().parent().parent().find('.bgc-gray-darkest').hide();
			 \$form.parent().parent().parent().parent().find('.formcontentotherfeedback').show();
				\$form.parent().parent().parent().parent().find('.formcontentotherfeedback #hiden').val(1);
				
				
	   			
				
				
    		}else{
				
				$(document).find('#feedback').html('Something went wrong').show();
				 
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
		
			  },
			  onClose: function(){
				  location.reload();
			  }
		});
		
		handler.openIframe();
		
  }
  
	
	function createOrder(planid){
		$.post('$cashAprovedUrl'+'?amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   		$(document).find('.bgc-gray-darkest').hide();
	   			$(document).find('#feedback').html('Sent').show();
				$(document).find('.bgc-gray-darkest').hide();
				$(document).find('.formcontentotherfeedback').slideDown();
				$.pjax.reload({container:"#firstcart",async: false}); 
			 $.pjax.reload({container:"#firstcart2",async: false}); 
			 $.pjax.reload({container:"#firstcart3",async: false}); 
			 $('.formcontentotherfeedback').show();
				\$form.parent().parent().parent().parent().find('.formcontentotherfeedback #hiden').val(1);
				
    		}else{
				
				$(document).find('#feedback').html('Payment Was not successfull').show();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	}
	
	if(paymentMode == 'wallet'){
	
		$.post('$walletUrl'+'?amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
				countdownexploder();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Not enought funds in wallet').show();
				countdownexploder();
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	}else if(paymentMode == 'transfer'){
	   
	
		$.post('$transferUrl'+'?ordertype=data',\$form.serialize())
		.always(function(result){
	
			$(document).find('.actualamount').html('$actualAmountUrlmain');
   			if(result==1){
	   			$('#BtnLoader').hide();
	   			$(document).find('#feedback').html('Sent').show();
				\$form.parent().parent().parent().parent().find('.bgc-gray-darkest').hide();
			 \$form.parent().parent().parent().parent().find('.formcontentotherfeedback').show();
				\$form.parent().parent().parent().parent().find('.formcontentotherfeedback #hiden').val(2);
				
				
				
				
    		}else{
				alert('error')
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if (paymentMode == 'card'){
		$.post('$cardValidationUrl'+'?amountid='+planid,\$form.serialize())
		.always(function(result){
	
			
   			if(result.success==1){
				
				customerEmail = result.email;
				if(customerEmail.lenght == 0){
				 customerEmail = 'kingsonly13c@gmail.com';
				}
				
				payWithPaystack(customerEmail,result.amount,createOrder);
				
				
    		}else{
				
				$(document).find('#feedback').html('Not enought funds in wallet').show();
				setTimeout(function(){ 
				$(document).find('#feedback').hide();
				$(document).find('#BtnLoader').hide();
				$(document).find('#submitButtonText').show();
				$.pjax.reload({container:"#buy_data",async: false}); 
				}, 5000);
	
				
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else if (paymentMode == 'voucher'){
			var pin = $('#pin').val();
			$.post('$voucheUrl'+'?pin='+pin+'& amountid='+planid+'& ordertype=data',\$form.serialize())
		.always(function(result){
	
			$(document).find('#loader').hide();
   			if(result==1){
			$('#BtnLoader').hide();
	   
	   			
	   			$(document).find('#feedback').html('Sent').show();
				$(document).find('.bgc-gray-darkest').hide();
				$(document).find('.formcontentotherfeedback').slideDown();
				countdownexploder();
    		}else{
				$('#BtnLoader').hide();
				$(document).find('#feedback').html('Invalid or Pin used').show();
				countdownexploder();
	
    		}
    	}).fail(function(){
    		console.log('Server Error');
    	});
	} else{
		alert('no option selected');
	}
    
	
	
    return false;
 	
    
});


JS;
 
$this->registerJs($order);
?>